[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bagheera-suite"
version = "1.0.0"
authors = [{ name="Ignacio Serantes" }]
description = "Bagheera Suite: Search Tool and Image Viewer for KDE/Baloo"
readme = "README.md"
requires-python = ">=3.8"
license = {text = "GPL-3.0-or-later"}
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Framework :: KDE",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Topic :: Multimedia :: Graphics :: Viewers",
]
dependencies = [
    "lmdb",
    "pyparsing",
    "PySide6",
    "psutil",
    "watchdog",
    "imagehash",
]

[project.optional-dependencies]
all = [
    "exiv2",
    "face-recognition",
    "face_recognition_models",
    "faiss-cpu",
    "faiss-gpu",
    "mediapipe",
    "pytest",
]
exiv = ["exiv2"]
faces = [
    "face-recognition",
    "face_recognition_models",
    "mediapipe"
]
duplicates = [
    "faiss-cpu",
    "faiss-gpu"
]
test = ["pytest"]

[project.scripts]
bagheerasearch = "bagheerasearch.core.app:main"
bagheeragui = "bagheeragui.gui.main:main"
bagheeraview = "bagheeraview.core.app:main"

[tool.setuptools]
package-dir = {"" = "src"}
zip-safe = false

[tool.setuptools.packages.find]
where = ["src"]
include = ["bagheerasearch*", "bagheeraview*", "bagheeragui*"]

[tool.setuptools.package-data]
"*" = ["libbaloo_wrapper.so"]
"bagheeragui" = ["assets/*"]
"bagheeraview" = ["assets/*"]
